from datetime import date
from decimal import Decimal

from accounts import BankAccount, InvestmentAccount, PremiumAccount, SavingsAccount
from shared.enums import Currency, TransactionPriority, TransactionType

DEMO_SCHEDULE_NAMES = {"afternoon", "night"}
ACCOUNT_PREPARATION_ACTIONS = {"deposit", "apply_monthly_interest", "invest_in_asset", "freeze"}

CLIENT_DEFINITIONS = {
    "alice": {
        "full_name": "Alice River",
        "birth_date": date(1990, 1, 10),
        "contacts": {"phone": "+10000000001", "email": "alice@example.com"},
        "pin_code": "1111",
    },
    "bob": {
        "full_name": "Bob Stone",
        "birth_date": date(1991, 2, 11),
        "contacts": {"phone": "+10000000002", "email": "bob@example.com"},
        "pin_code": "2222",
    },
    "carol": {
        "full_name": "Carol Frost",
        "birth_date": date(1989, 3, 12),
        "contacts": {"phone": "+10000000003", "email": "carol@example.com"},
        "pin_code": "3333",
    },
    "dave": {
        "full_name": "Dave Snow",
        "birth_date": date(1988, 4, 13),
        "contacts": {"phone": "+10000000004", "email": "dave@example.com"},
        "pin_code": "4444",
    },
    "emma": {
        "full_name": "Emma Lake",
        "birth_date": date(1992, 5, 14),
        "contacts": {"phone": "+10000000005", "email": "emma@example.com"},
        "pin_code": "5555",
    },
    "frank": {
        "full_name": "Frank Woods",
        "birth_date": date(1987, 6, 15),
        "contacts": {"phone": "+10000000006", "email": "frank@example.com"},
        "pin_code": "6666",
    },
}

ACCOUNT_DEFINITIONS = {
    "alice_main": {"client": "alice", "account_type": BankAccount, "currency": Currency.USD},
    "alice_savings": {
        "client": "alice",
        "account_type": SavingsAccount,
        "currency": Currency.EUR,
        "min_balance": 100,
        "monthly_interest_rate": Decimal("0.01"),
    },
    "bob_main": {"client": "bob", "account_type": BankAccount, "currency": Currency.USD},
    "bob_invest": {"client": "bob", "account_type": InvestmentAccount, "currency": Currency.USD},
    "carol_premium": {
        "client": "carol",
        "account_type": PremiumAccount,
        "currency": Currency.USD,
        "overdraft_limit": 500,
        "withdrawal_limit": 1500,
        "fixed_fee": 10,
    },
    "carol_rub": {"client": "carol", "account_type": BankAccount, "currency": Currency.RUB},
    "dave_main": {"client": "dave", "account_type": BankAccount, "currency": Currency.USD},
    "dave_savings": {
        "client": "dave",
        "account_type": SavingsAccount,
        "currency": Currency.USD,
        "min_balance": 50,
        "monthly_interest_rate": Decimal("0.015"),
    },
    "emma_main": {"client": "emma", "account_type": BankAccount, "currency": Currency.KZT},
    "emma_premium": {
        "client": "emma",
        "account_type": PremiumAccount,
        "currency": Currency.USD,
        "overdraft_limit": 400,
        "withdrawal_limit": 800,
        "fixed_fee": 5,
    },
    "frank_main": {"client": "frank", "account_type": BankAccount, "currency": Currency.EUR},
    "frank_invest": {"client": "frank", "account_type": InvestmentAccount, "currency": Currency.USD},
}

ACCOUNT_PREPARATION_STEPS = (
    {"action": "deposit", "account": "alice_main", "amount": 4000},
    {"action": "deposit", "account": "alice_savings", "amount": 1200},
    {"action": "apply_monthly_interest", "account": "alice_savings"},
    {"action": "deposit", "account": "bob_main", "amount": 2500},
    {"action": "deposit", "account": "bob_invest", "amount": 5000},
    {"action": "invest_in_asset", "account": "bob_invest", "asset_type": "stocks", "amount": 2000},
    {"action": "invest_in_asset", "account": "bob_invest", "asset_type": "etf", "amount": 1000},
    {"action": "deposit", "account": "carol_premium", "amount": 300},
    {"action": "deposit", "account": "carol_rub", "amount": 150000},
    {"action": "deposit", "account": "dave_main", "amount": 600},
    {"action": "deposit", "account": "dave_savings", "amount": 800},
    {"action": "deposit", "account": "emma_main", "amount": 80000},
    {"action": "deposit", "account": "emma_premium", "amount": 200},
    {"action": "deposit", "account": "frank_main", "amount": 1800},
    {"action": "deposit", "account": "frank_invest", "amount": 4000},
    {"action": "invest_in_asset", "account": "frank_invest", "asset_type": "bonds", "amount": 1500},
    {"action": "invest_in_asset", "account": "frank_invest", "asset_type": "etf", "amount": 500},
    {"action": "freeze", "account": "dave_main"},
)

TRANSACTION_GROUP_DEFINITIONS = (
    {
        "schedule": None,
        "cases": (
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 150,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_account": "bob_main",
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 100,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_account": "alice_savings",
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 120,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("retail", 1),
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 250,
                "currency": Currency.USD,
                "sender": "carol_premium",
                "recipient_external": ("vendor", 1),
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 200,
                "currency": Currency.EUR,
                "sender": "frank_main",
                "recipient_account": "bob_main",
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 10000,
                "currency": Currency.KZT,
                "sender": "emma_main",
                "recipient_external": ("kzt", 1),
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 250,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_account": "dave_savings",
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 80,
                "currency": Currency.EUR,
                "sender": "alice_savings",
                "recipient_account": "frank_main",
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 50,
                "currency": Currency.EUR,
                "sender": "frank_main",
                "recipient_external": ("eur", 1),
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 50,
                "currency": Currency.USD,
                "sender": "emma_premium",
                "recipient_external": ("usd", 1),
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 75,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_account": "carol_rub",
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 300,
                "currency": Currency.USD,
                "sender": "bob_invest",
                "recipient_external": ("usd", 2),
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 200,
                "currency": Currency.USD,
                "sender": "frank_invest",
                "recipient_account": "alice_main",
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 100,
                "currency": Currency.USD,
                "sender": "dave_savings",
                "recipient_account": "alice_main",
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 40,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("missing_demo_account", None),
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 60,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_account": "dave_main",
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 50,
                "currency": Currency.USD,
                "sender": "dave_main",
                "recipient_account": "bob_main",
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 5000,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_external": ("usd", 3),
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 450,
                "currency": Currency.USD,
                "sender": "carol_premium",
                "recipient_external": ("usd", 4),
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 130,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_account": "bob_main",
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 1200,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("risk", 1),
                "priority": TransactionPriority.HIGH,
            },
        ),
    },
    {
        "schedule": None,
        "cases": (
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 90,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("risk", 2),
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 95,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("risk", 3),
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 100,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("risk", 4),
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 70,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_account": "bob_main",
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 110,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("risk", 5),
            },
        ),
    },
    {
        "schedule": "afternoon",
        "cases": (
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 100,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_account": "frank_main",
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 5000,
                "currency": Currency.KZT,
                "sender": "emma_main",
                "recipient_account": "alice_main",
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 250,
                "currency": Currency.USD,
                "sender": "frank_invest",
                "recipient_external": ("usd", 5),
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 1000,
                "currency": Currency.RUB,
                "sender": "carol_rub",
                "recipient_external": ("rub", 1),
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 1200,
                "currency": Currency.USD,
                "sender": "dave_savings",
                "recipient_external": ("usd", 6),
                "priority": TransactionPriority.HIGH,
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 80,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_external": ("usd", 7),
            },
        ),
    },
    {
        "schedule": "night",
        "cases": (
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 60,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_external": ("night", 1),
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 2000,
                "currency": Currency.KZT,
                "sender": "emma_main",
                "recipient_external": ("night", 2),
                "priority": TransactionPriority.LOW,
            },
            {
                "transaction_type": TransactionType.INTERNAL_TRANSFER,
                "amount": 70,
                "currency": Currency.EUR,
                "sender": "frank_main",
                "recipient_account": "alice_main",
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 1500,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("night", 3),
                "priority": TransactionPriority.HIGH,
            },
        ),
    },
    {
        "schedule": None,
        "cases": (
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 40,
                "currency": Currency.USD,
                "sender": "alice_main",
                "recipient_external": ("cancel", 1),
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 55,
                "currency": Currency.USD,
                "sender": "bob_main",
                "recipient_external": ("cancel", 2),
                "scheduled_for": "afternoon",
            },
            {
                "transaction_type": TransactionType.EXTERNAL_TRANSFER,
                "amount": 65,
                "currency": Currency.EUR,
                "sender": "frank_main",
                "recipient_external": ("cancel", 3),
                "priority": TransactionPriority.LOW,
                "scheduled_for": "night",
            },
        ),
    },
)
